### ISSUE TITLE
Fix error handling in JAX-RS integration libraries

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-restful-integration#25]
We currently use:

```java
new Error(code, message)
```

... instead of:

```java
new ErrorResponse(code, message)
```

... in our JAX-RS SDK, which is not consistent with documentation and other components.

Before we fix this issue, we need to make sure that our customers are not relying on the faulty behavior, and if they are, we need to prepare a backward compatible solution.

**Comment by petrdvorak** [comment]
See here for more details:

- https://github.com/lime-company/powerauth-restful-integration/tree/develop/powerauth-restful-security-javaee/src/main/java/io/getlime/security/powerauth/rest/api/jaxrs/exception

**Comment by petrdvorak** [comment]
Verified, seems that we can fix this one...

**Comment by romanstrobl** [comment]
Good, I will look into this.
