### ISSUE TITLE
Create endpoint for signature verification

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-restful-integration#26]
Currently e.g. PIN verification calls vault unlock, because there is no endpoint to verify signature.

**Comment by petrdvorak** [comment]
Just a little discussion to this issue: What signature types should we validate? Do we have some usecase for validating 1FA signatures, or should we only validate 2FA, namely `possession_knowledge` and `possession_biometry`?

**Comment by petrdvorak** [comment]
- We need to publish endpoint that validates only 2FA signatures - `possession_knowledge` and `possession_biometry `
- We can have also validation for `possession_knowledge_biometry`.
- The method should be able to accept all HTTP methods.
- It should accept any arbitrary request body (`Object`).

**Comment by romanstrobl** [comment]
Any suggestions for endpoint name? We already use `/pa/signature/validate` in RESTful server, so we'll need another name to avoid collision of request mappings.

**Comment by hvge** [comment]
I'm just curious, but what's difference between that `/pa/signature/validate` and `/pa/login/validate`? The mobile SDK must point to just one endpoint, so which one I'll need to implement?

**Comment by petrdvorak** [comment]
`/pa/signature/validate` is the correct endpoint. The other one is used in back-end integration examples, as a way to show how login is done...

**Comment by romanstrobl** [comment]
I also renamed the `/pa/login/validate` to just `/login` in examples in this commit, so there is no `/pa/login/validate` endpoint. This should avoid any confusion.
