### ISSUE TITLE
powerauth-restful-model is broken on Android platform

### ISSUE THREAD

**Issue by hvge** [lime-company/powerauth-restful-integration#6]
The `0.17.0` version of `io.getlime.security:powerauth-restful-model` is broken on Android platform. It depends on guava and other unwanted libraries and the compiled byte code is not compatible with internal class to dex convertor. 

I've created the ticket in this repo (because mobile sdk depends on it), but the source of the problem is in `io.getlime.core:rest-model-base`, which actually adds all that unwanted dependencies.

**Comment by petrdvorak** [comment]
Oh boy... let the "release cascade" begin...

`rest-model-base => powerauth-restful-model => powerauth-restful-security-* => powerauth-webflow`
